# Generated by Django 5.0.4 on 2024-05-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_description_alter_video_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='kind',
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.URLField(),
        ),
    ]
