# Generated by Django 5.0.4 on 2024-05-21 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_name'),
        ('videos', '0006_video_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='categories',
        ),
        migrations.AddField(
            model_name='video',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
    ]
