# Generated by Django 5.0.4 on 2024-04-18 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_subscribe'),
        ('videos', '0002_video_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likeVideo',
            field=models.ManyToManyField(related_name='user_likeVideo', to='videos.video'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribe',
            field=models.ManyToManyField(related_name='user_subscribe', to=settings.AUTH_USER_MODEL),
        ),
    ]
