# Generated by Django 5.0.4 on 2024-04-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_likevideo_alter_user_subscribe'),
        ('videos', '0002_video_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alert',
            field=models.ManyToManyField(related_name='user_alert', to='videos.video'),
        ),
    ]
