# Generated by Django 5.0.4 on 2024-05-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_alter_comment_review'),
        ('users', '0005_user_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likeComment',
            field=models.ManyToManyField(blank=True, null=True, related_name='comment_like', to='comments.comment'),
        ),
    ]
