# Generated by Django 5.0.4 on 2024-05-19 08:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alert',
            field=models.ManyToManyField(related_name='user_alert', to=settings.AUTH_USER_MODEL),
        ),
    ]
