# Generated by Django 5.0.4 on 2024-05-21 04:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_image'),
        ('videos', '0006_video_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alert',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_alert', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='likeVideo',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_likeVideo', to='videos.video'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribe',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_subscribe', to=settings.AUTH_USER_MODEL),
        ),
    ]
