# Generated by Django 5.0.4 on 2024-05-27 03:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_rename_content_comment_content_video_and_more'),
        ('users', '0011_alter_user_alert_alter_user_image_and_more'),
        ('videos', '0007_remove_video_categories_video_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recent_video',
            field=models.ManyToManyField(blank=True, related_name='recent_video', to='videos.video'),
        ),
        migrations.AlterField(
            model_name='user',
            name='alert',
            field=models.ManyToManyField(blank=True, related_name='user_alert', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='likeComment',
            field=models.ManyToManyField(blank=True, related_name='comment_like', to='comments.comment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='likeVideo',
            field=models.ManyToManyField(blank=True, related_name='user_likeVideo', to='videos.video'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribe',
            field=models.ManyToManyField(blank=True, related_name='user_subscribe', to=settings.AUTH_USER_MODEL),
        ),
    ]
