# Generated by Django 5.0.4 on 2024-05-27 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_recent_video_alter_user_alert_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='recent_video',
            new_name='recent_videos',
        ),
    ]
