# Generated by Django 5.0.4 on 2024-05-31 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_recent_video_user_recent_videos'),
        ('videos', '0007_remove_video_categories_video_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='recent_videos',
        ),
        migrations.AddField(
            model_name='user',
            name='recent_video1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_recent_video1', to='videos.video'),
        ),
        migrations.AddField(
            model_name='user',
            name='recent_video2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_recent_video2', to='videos.video'),
        ),
        migrations.AddField(
            model_name='user',
            name='recent_video3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_recent_video3', to='videos.video'),
        ),
        migrations.AddField(
            model_name='user',
            name='recent_video4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_recent_video4', to='videos.video'),
        ),
        migrations.AddField(
            model_name='user',
            name='recent_video5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_recent_video5', to='videos.video'),
        ),
    ]
