# Generated by Django 5.0.4 on 2024-04-23 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_review_alter_comment_content'),
        ('videos', '0003_video_description_alter_video_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='videos.video'),
        ),
    ]
